server:
  port: 9001

spring:
  boot:
    admin:
      client:
        url: http://localhost:9004
  application:
    name: template-admin
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      default Zone: http://localhost:8080/eureka/